filebeat.inputs:
  - type: filestream
    id: docker-containers
    paths:
      - /var/lib/docker/containers/*/*.log
    parsers:
      - container: ~
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - drop_event:
          when:
            not:
              or:
                - equals:
                    container.name: "bot-restaurantes"
                - equals:
                    container.name: "elasticsearch"
                - equals:
                    container.name: "kibana"

processors:
  - add_host_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"

setup.ilm.enabled: true
setup.ilm.rollover_alias: "bot-logs"
setup.ilm.pattern: "{now/d}-000001"
setup.ilm.policy_name: "bot-2d-policy"
setup.ilm.overwrite: true
setup.ilm.policy_file: /usr/share/filebeat/ilm-policy.json

setup.template.name: "bot-logs"
setup.template.pattern: "bot-logs-*"
setup.template.overwrite: true

logging.level: info
